config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'index#input'

  get 'session/login'
  get 'session/create'
  get 'session/logout'
  get 'session/registrate'
  get 'session/update'
  resources :users
  
  get 'index/output'
  post 'index/add'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/index.rb
class Index < ApplicationRecord
  validates :array, presence: true, uniqueness: true

  class << self
      def create_from_arr(arr, res, err, long)
        create array: arr, result: res, error: err, longest_one: long
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, uniqueness: true
    has_secure_password

    def update_last_login_at
        self.last_login_at = DateTime.now
        save
    end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
    include SessionHelper

    before_action :require_login

    private

    def require_login
        unless signed_in?
            flash[:danger] = 'Требуется логин'
            redirect_to session_login_url
        end
    end
end

app/controllers/index_controller.rb
# frozen_string_literal: true

require 'json'

class IndexController < ApplicationController
  before_action :parse_params, only: :output

  def input; end

  def output
    find_res = Index.find_by(array: @array)
    if find_res.nil?
      @result = Solve.call @array
      if @result.nil?
        @error = 'Некорректный ввод'
      elsif @result.length.positive?
        @longest_one = @result[@result.map { |a| a[0].length }.each_with_index.max[1]]
      end
      add if @error.nil?
    else
      parse_find_res(find_res)
    end
  end

  private

  def parse_params
    # Normalize array before action
    @array = params[:a]&.strip&.split&.join(' ')
  end

  def add
    Index.create_from_arr(@array, @result, !@error.nil?, @longest_one)
  end

  def parse_find_res(find_res)
    @error = find_res.result ? 'Некорректный ввод' : nil
    unless @error.nil?
      @result = JSON.parse(find_res.result)
      @longest_one = JSON.parse(find_res.longest_one) if !find_res.longest_one.nil?
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :require_login, only: %i[login create registrate]

  def login
  end

  def registrate
    if !params[:login].nil?
      @user = User.find_by(username: params[:login])
      if @user.nil? && (params[:password] == params[:password_confirm])
        @user = User.new username: params[:login], password: params[:password]
        @user.save
        sign_in @user
        redirect_to root_path
      end
    end
  end

  def create
    @user = User.find_by(username: params[:login])

    if @user&.authenticate(params[:password])
      sign_in @user
      redirect_to root_path
    else
      flash.now[:danger] = 'Неверный логин или пароль'
      redirect_to session_login_path
    end
  end

  def update
    user_here = current_user
    p "/users/#{user_here.id}/edit"
    redirect_to "/users/#{user_here.id}/edit"
  end

  def logout
    sign_out
    redirect_to session_login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :password_digest, :last_login_at)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/index_helper.rb
# frozen_string_literal: true

module IndexHelper
end

app/helpers/session_helper.rb
module SessionHelper
    def sign_in(user)
        cookies.signed[:user_id] = { value: user.id, expires: 10.days }
        user.update_last_login_at
        self.current_user = user
    end

    def signed_in?
        !current_user.nil?
    end

    def sign_out
        cookies.signed[:user_id] = nil
        self.current_user = nil
    end

    def current_user=(user)
        @current_user = user
    end

    def current_user
        @current_user ||= User.find_by(id: cookies.signed[:user_id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/index/ajax_output.js.erb
var res = `

<div id="result_output">
    <div class="container">
        <div class="row">
            <div class="col-5">

                <% if not @result.nil? %>
                    <% if not @longest_one.nil? %>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Отрезки</th>
                                    <th scope="col">Индексы</th>
                                </tr>
                            </thead>
                            <tbody>
                            
                                <% @result.each_with_index do |r, i| %>
                                    <tr>
                                        <th scope="row"> <%= i+1 %>  </th>
                                        <td> <p> <%= r[0] %> </p> </td>
                                        <td> <p> <%= r[1] %> </p> </td>
                                    </tr>
                                <% end %>
                                
                            </tbody>
                        </table>  

                        <p> <%= @longest_one[0] %> :: <%= @longest_one[1] %> </p>

                    <% else %>
                        <p> Отрезков не нашлось... </p>
                    <% end %>

                <% else %>
                    <p> <%= @error %>  </p>
                <% end %>  

            </div>
        </div>
    </div>
</div>
`;

document.querySelector('#result').innerHTML = res;

app/views/index/input.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>Главная страница</title>
<meta name='viewport' content='width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no'/>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
     <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <h4 class="my-0 mr-md-auto font-weight-normal">Шахов Станислав ИУ6-33Б</h4>
    </div>

    <div class="container">
        <p class="fs-6">
        Написать программу, которая вводит цепочку целых чисел (количество чисел не менее 10)
        и определяет наиболее длинную монотонно возрастающую их последовательность. 
        Вывести на печать введенную цепочку, все найденные последовательности и 
        наиболее длинную из них. При программировании использовать функцию.
        </p>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-3">
                <form action="<%= index_output_url %>">
                    <div class="mb-3">
                        <input name="a" required="required" class="form-control">
                    </div>
                    <input type="submit" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>


     <div class="container">
        <div class="row">
            <div class="col-3">
                <div><%= link_to 'Update', session_update_path %></div>
            </div>
        </div>
        <div class="row">
            <div class="col-3">
                <div><%= link_to 'Log Out', session_logout_path %></div>
            </div>
        </div>
    </div>
</body>
</html>

app/views/index/output.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>Решение задачи</title>
<meta name='viewport' content='width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no'/>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
     <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <h4 class="my-0 mr-md-auto font-weight-normal">Шахов Станислав ИУ6-33Б</h4>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-5">

                <% if not @result.nil? %>
                    <% if not @longest_one.nil? %>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Отрезки</th>
                                    <th scope="col">Индексы</th>
                                </tr>
                            </thead>
                            <tbody>
                            
                                <% @result.each_with_index do |r, i| %>
                                    <tr>
                                        <th scope="row"> <%= i+1 %>  </th>
                                        <td> <p> <%= r[0] %> </p> </td>
                                        <td> <p> <%= r[1] %> </p> </td>
                                    </tr>
                                <% end %>
                                
                            </tbody>
                        </table>  

                        <p> <%= @longest_one[0] %> :: <%= @longest_one[1] %> </p>

                    <% else %>
                        <p> Отрезков не нашлось... </p>
                    <% end %>

                <% else %>
                    <p> <%= @error %>  </p>
                <% end %>  

            </div>
        </div>
    </div>
    
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lr8New</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/login.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>Главная страница</title>
<meta name='viewport' content='width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no'/>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>

    <div class="container">
        <div class="row">
            <div class="col-5">
                <form action="<%= session_create_url %>">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Login</label>
                        <input name="login"  class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter login">
                        <small id="emailHelp" class="form-text text-muted">We'll never share your login with anyone else.</small>
                    </div>

                    <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        <input name="password" type="password" class="form-control" placeholder="Password">
                    </div>

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
                <div>
                    <%= link_to 'Registrate', session_registrate_path %>
                </div>
            </div>
        </div>
    </div>
    
</body>
</html>

app/views/session/logout.html.erb
<h1>Session#logout</h1>
<p>Find me in app/views/session/logout.html.erb</p>

app/views/session/registrate.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>Главная страница</title>
<meta name='viewport' content='width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no'/>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>

    <div class="container">
        <div class="row">
            <div class="col-3">
                <form action="<%= session_registrate_url %>">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Login</label>
                        <input name="login"  class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter login">
                    </div>

                    <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        <input name="password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                    </div>

                    <div class="form-group">
                        <label for="exampleInputPassword1">Password Confirm</label>
                        <input name="password_confirm" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                    </div>
                    <p>
                        <button type="submit" class="btn btn-primary">Registrate</button>
                    </p>
                    
                </form>
            </div>
        </div>
    </div>
    
</body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password_digest %>
    <%= form.text_field :password_digest %>
  </div>

  <div class="field">
    <%= form.label :last_login_at %>
    <%= form.datetime_select :last_login_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password digest</th>
      <th>Last login at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.last_login_at %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<p>
  <strong>Last login at:</strong>
  <%= @user.last_login_at %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>